name: Build and Publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build the Docker image and push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: |
            sukovanej/stylua:latest
            sukovanej/stylua:1.0
          push: ${{ github.ref == 'refs/heads/master' }}
